### ISSUE TITLE
大哥，你Casper主题改了啥？

### ISSUE THREAD

**Issue by qiansen1386** [fatestigma/fatestigma.github.io#1]
我也想用Casper，只是看到你博客里提到这个主题其实适合多作者而非单一作者，这我就有点方了。能不能问下这个差别主要体现在哪里？

**Comment by fatestigma** [comment]
其实目前还和 Casper 没啥大差别，本来是打算大改的，后来一直没时间就搁置了。目前改了的地方不多：1. single 的模板里添加返回按钮。 2. 部分地方汉化。 3. 字体和版式修改，Casper 主要西文排版还可以，中文差了些。 应该目前就这些吧，很多地方都还没动。
另外关于多作者的，Casper 主题在每篇日志的 front matter 中都有 `author` 这一条，可以对应到 `data/authors/` 中的对应作者配置文件。单一作者的博客主题是不需要再日志列表的每篇日志左下方都注明作者姓名的。这也是为何我说 Casper 适合多作者博客（如知乎专栏的一个专栏可以有多个人写），如果不在意也没有什么关系。

**Comment by qiansen1386** [comment]
这样啊。多谢大神

**Comment by qiansen1386** [comment]
参考您的教程，我的automation设置成功了！
[qiansen1386.github.io](https://qiansen1386.github.io)
多谢大哥

感觉我选的这个主题，略奇怪，大小字体页宽啥的，我都得改一改……Orz
